End to End Deep learning project using RNN

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [ ]:
#loading imdb dataset
max_features = 10000 #number of words to consider as features
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

#Print the shape of data
print(f'training data shape: {x_train.shape},training labels shape: { y_train.shape}')
print(f'tetsing data shape:{x_test.shape}, testing label shape: {y_test.shape}')

In [ ]:
#Inspect a sample review and its label
sample_review = x_train[0]
sample_label = y_train[0]
print(f'Sample review(as integers):{sample_review}')
print(f'sample label:{sample_label}')

In [ ]:
#Mapping of index back to words(for understanding the review)
word_index = imdb.get_word_index()
word_index
reverse_word_index = {value:key for key,value in word_index.items()}
reverse_word_index

In [14]:
from tensorflow.keras.preprocessing import sequence
max_len=500
x_train = sequence.pad_sequences(x_train,maxlen=max_len)
x_test =sequence.pad_sequences(x_test,maxlen=max_len)
print(x_train)
print(y_train)


[[   0    0    0 ...   19  178   32]
 [   0    0    0 ...   16  145   95]
 [   0    0    0 ...    7  129  113]
 ...
 [   0    0    0 ...    4 3586    2]
 [   0    0    0 ...   12    9   23]
 [   0    0    0 ...  204  131    9]]
[1 0 0 ... 0 1 0]
